export type UserKey = 'user'
export type FavoritesAmountKey = 'favoritesAmount'
export type FavoritesItemsKey = 'favoriteItems'
export type Active = 'active'
export type SearchFormId = 'search-form'
export type ToggleIdPrefix = 'toggle-'
export type ToBookIdPrefix = 'to-book-'
